services:
  - type: web
   name: idzonez
   env: node
   buildCommand: npm install
   startCommand: node server.js
   envVars:
     - key: PORT
       value: 3000
     - key: BASE_URL
       value: https://idzonez.com
     - key: ALLOWED_ORIGIN
       value: https://www.idzonez.com
     - key: JWT_SECRET
       sync: false
     - key: ADMIN_USERNAME
       sync: false
     - key: ADMIN_PASSWORD
       sync: false
